AI連携時にローディングを表示
Misoten-B/airship-frontend pull request #146
Opened 2023-12-25 10:14 UTC by nakamura0907

### 関連issue

- close #145 

### 説明

### その他

2023-12-25 23:18 UTC, mitsuYashi commented on src/app/ar-assets/create/_components/StepContent/UploadQRCodeInsideImage/index.tsx
> +      toggleLoading();
これほんとにtoggleで大丈夫か

2023-12-25 23:18 UTC, mitsuYashi commented on src/app/ar-assets/create/_components/StepContent/UploadQRCodeInsideImage/index.tsx
> +      toggleLoading();
バグる可能性ない？

2023-12-26 03:32 UTC, nakamura0907 commented on src/app/ar-assets/create/_components/StepContent/UploadQRCodeInsideImage/index.tsx
> +      toggleLoading();
あるかもしれんし、ないかもしれん
少なくとも正常系の時は動作確認した

2023-12-26 06:58 UTC, mitsuYashi commented on src/app/ar-assets/create/_components/StepContent/UploadQRCodeInsideImage/index.tsx
> +      toggleLoading();
openとcloseみたいに変えられん？

2023-12-26 07:51 UTC, mitsuYashi requested changes
お願いします

2023-12-26 09:55 UTC, mitsuYashi commented
@nakamura0907 こっちで受け持っていい？

2023-12-26 12:16 UTC, mitsuYashi approved these changes

2023-12-26 12:19 UTC, merged