add:mantine Modal作成
Misoten-B/airship-frontend pull request #92
Opened 2023-12-12 06:55 UTC by SadoharaYutaka

### 関連issue

- close #91 

### 説明
選択するボタンをおしたらModalが開くようにしました
<img width="671" alt="スクリーンショット 2023-12-12 15 50 11" src="https://github.com/Misoten-B/airship-frontend/assets/85974240/782124c0-6c33-4f57-b614-4a7dd01e0069">

Modal画面
<img width="445" alt="スクリーンショット 2023-12-12 15 23 50" src="https://github.com/Misoten-B/airship-frontend/assets/85974240/0e9d7d65-43be-4a0b-a772-ad7a0e80baf8">

Modal  componentsの追加

### その他

2023-12-12 07:06 UTC, mitsuYashi requested changes

2023-12-12 07:06 UTC, mitsuYashi commented on src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/Display3dModel.tsx
> +import { useDisclosure } from '@mantine/hooks';
これsharedに切り出して

2023-12-12 07:40 UTC, SadoharaYutaka commented on src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/Display3dModel.tsx
> +import { useDisclosure } from '@mantine/hooks';
useDisclosureのcomponentsをつくるってこと？

2023-12-12 07:43 UTC, mitsuYashi commented on src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/Display3dModel.tsx
> +import { useDisclosure } from '@mantine/hooks';
`/airship-frontend/src/shared/hooks/`があるからこの中に。
`use~~`(useState, useEffectとか)ってやつはhooksって呼ばれてるからcomponentsとは別扱い

2023-12-14 03:00 UTC, mitsuYashi approved these changes

2023-12-14 03:01 UTC, mitsuYashi commented
@honoka2001 こまかいとこ見といて

2023-12-14 05:47 UTC, honoka2001 approved these changes
LGTM！

2023-12-14 05:47 UTC, merged